### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [wak-sudo/PongPDCurses#1]
Hi, this looks interesting, and nice for learning C/C++ and PDCurses. Which license applies to this project?

**Comment by wak-sudo** [comment]
I have attached the MIT license.

As for learning from this code - it can be improved. In particular, the program should not use so many threads recklessly. Ideally, multithreading should be eliminated.

**Comment by LifeCANvs** [comment]
> I have attached the MIT license.
> 
> As for learning from this code - it can be improved. In particular, the program should not use so many threads recklessly. Ideally, multithreading should be eliminated.

Thanks for making your code available to learn from, and thanks also for the advice! That will be part of the learning process for me (finding what can be improved and how to do it) :)
